[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_withdraw_10_deposit = "3Ym3aCtqvj78Y1M7k9yPPxeL4V49uY16LKk24qiuwd3z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/saitamacoder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
